routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['throttle:60,1'])->namespace('Auth')->group(function() {
    Route::get('/login/google', 'LoginController@google')->name('google.login');
    Route::get('/login/google/callback', 'LoginController@googleCallback')->name('google.callback');
});

Route::redirect('/', '/login');

Route::get('dashboard', 'DashboardController@index')->name('dashboard');
Route::post('search', 'DashboardController@suggestions')->name('search.suggestions');

Route::get('asana', 'AsanaServiceController')->name('asana');

Route::resource('appointments', 'AppointmentController');
Route::resource('clients', 'ClientController');
Route::resource('users', 'UserController');
Route::resource('settings', 'SettingController');

Route::prefix('')->group(function() {
    Route::resource('invoices', 'InvoiceController');
    Route::get('quickbooks/invoice', 'InvoiceController@invoice')->name('invoices.quickbooks');
    Route::get('quickbooks/invoice/callback', 'InvoiceController@invoiceCallback')->name('invoices.quickbooks.callback');
    Route::get('quickbooks/invoice/{invoice}/void', 'InvoiceController@void')->name('invoice.void');
    Route::get('quickbooks/invoice/{invoice}/sendemail', 'InvoiceController@sendEmail')->name('invoice.send');
});

Route::prefix('')->group(function() {
    Route::resource('templates', 'TemplateController');
    Route::get('/{template}/fill', 'TemplateController@fill')->name('templates.fill');
    Route::post('/ckeditor/upload', 'TemplateController@uploadImage')->name('templates.ckeditor.upload');
});

Route::name('mail.')->prefix('mail')->group(function() {
    Route::get('/', 'MailController@compose')->name('compose');
    Route::post('/send', 'MailController@send')->name('send');
});

Route::put('clients/{client}/archive', 'ClientController@archive')->name('clients.archive');
Route::put('appointments/{appointment}/done', 'AppointmentController@done')->name('appointments.done');
Route::put('appointments/{appointment}/cancel', 'AppointmentController@cancel')->name('appointments.cancel');

Route::name('selections.')->prefix('selections')->group(function() {
    Route::get('tags', 'SelectController@tags')->name('tags');
    Route::get('clients', 'SelectController@clients')->name('clients');
    Route::get('templates', 'SelectController@templates')->name('templates');
    Route::get('groups', 'SelectController@groups')->name('groups');
    Route::get('roles', 'SelectController@roles')->name('roles');
});

// Temporary routes for discovery form
Route::view('discovery-form', 'discovery-form')->name('discovery.form');
Route::post('/discovery-call-intake', 'API\DiscoveryController@trigger')->name('discovery.trigger');

resources/views/compose.blade.php
@extends('layouts.app')

@section('title')
    Compose Email
@endsection

@push('head')
    <script src="https://cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
@endpush

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
    <div class="flex">
        @include('partials.aside')
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                <div class="flex justify-between">
                    <h1 class="text-2xl font-bold">Compose Email</h1>
                </div>
                @include('partials.messages')
                <div class="bg-white shadow sm:rounded-lg mt-5 p-5">
                    <form action="{{ route('mail.send') }}" method="post">
                        @csrf
                        <div class="flex flex-col mb-5">
                            <label for="template" class="font-bold text-gray-700 mb-1">Template </label>
                            <select class="w-full md:w-1/3" id="template"></select>
                        </div>
                        <div class="flex flex-col mb-5">
                            <label for="to" class="font-bold text-gray-700 mb-1">To <span class="text-red-500 text-xs">*</span></label>
                            <select class="w-full md:w-1/3" name="to" id="to"></select>
                        </div>
                        <div class="flex flex-col mb-5">
                            <label for="cc" class="font-bold text-gray-700 mb-1">Cc</label>
                            <select class="w-full md:w-1/3" name="cc[]" id="cc" multiple></select>
                        </div>
                        <div class="flex flex-col mb-5">
                            <label for="bcc" class="font-bold text-gray-700 mb-1">Bcc</label>
                            <select class="w-full md:w-1/3" name="bcc[]" id="bcc" multiple></select>
                        </div>
                        <div class="flex flex-col mb-5">
                            <label for="subject" class="font-bold text-gray-700 mb-1">Subject <span class="text-red-500 text-xs">*</span></label>
                            <input type="text" name="subject" id="subject" class="border-2 rounded w-full md:w-1/3" value="{{ old('subject') }}">
                        </div>
                        <div class="flex flex-col mb-5">
                            <label for="body" class="font-bold text-gray-700 mb-1">Body <span class="text-red-500 text-xs">*</span></label>
                            <textarea name="body" id="body" class="border-2 rounded w-full md:w-1/3" cols="30" rows="10">{{ old('body') }}</textarea>
                        </div>
                        <div class="flex flex-col mb-5">
                            <label for="attachments" class="font-bold text-gray-700 mb-1">Attachments</label>
                            <label class="w-64 flex flex-col items-center px-2 py-6 bg-white text-blue rounded-lg shadow-lg tracking-wide border border-blue cursor-pointer hover:bg-blue hover:text-white">
                                <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
                                </svg>
                                <input type="file" name="attachments[]" id="attachments" class="hidden" multiple/>
                            </label>
                        </div>
                        <div class="flex justify-end mt-10">
                            <button class="px-5 py-2 bg-admin-blue-dark text-white font-bold rounded-lg" type="submit">Send</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="{{ asset('js/insert_variable.js') }}"></script>
    <script>
        CKEDITOR.replace('body', {
            filebrowserImageUploadUrl: "{{ route('templates.ckeditor.upload', ['_token' => csrf_token() ])}}",
            filebrowserUploadMethod: 'form',
            extraPlugins: 'insert_variable',
            insert_variable: {
                variables: [
                    'To: First Name',
                    'To: Email',
                    'From: First Name',
                    'From: Email',
                ]
            },
        });

        $('select').select2({
            tags: true,
            tokenSeparators: [',', ' ']
        })
        $('#template').select2({
            ajax: {
                url: "{{ route('selections.templates') }}",
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: data.results
                    }
                },
                delay: 250,
                cache: true,
            },
            minimumInputLength: 1,
            tags: true,
            tokenSeparators: [',', ' ']
        });

        $('#to').select2({
            ajax: {
                url: "{{ route('selections.clients') }}",
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: data.results
                    }
                },
                delay: 250,
                cache: true,
            },
            templateResult: function (state) {
                if (! state.id) {
                    return state.text
                }
                return `${state.fullname} - ${state.text}`
            },
            templateSelection: function (state) {
                if (! state.id) {
                    return state.text
                }
                return `${state.text}`
            },
            minimumInputLength: 2,
        });

        $('#template').change(function () {
            var route = '{{ route("templates.fill", ":id") }}'
            route = route.replace(':id', this.value)

            $.get(route, function ({ template }) {
                fill(template)
            })
        })

        function fill({ to, bcc, cc, subject, body }) {
            // remove first
            $('#to option').remove()
            $('#bcc option').remove()
            $('#cc option').remove()

            // yolo
            if (to) to.forEach(item => { $('#to').append(`<option value=" ${item}" selected="selected"> ${item} </option>`)});
            if (bcc) bcc.forEach(item => { $('#bcc').append(`<option value=" ${item}" selected="selected"> ${item} </option>`)});
            if (cc) cc.forEach(item => { $('#cc').append(`<option value=" ${item}" selected="selected"> ${item} </option>`)});

            $('#subject').val(subject)
            CKEDITOR.instances['body'].setData(body)
        }

    </script>
@endpush

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('title')
    Dashboard
@endsection

@section('content')
    <div class="flex">

        {{-- Aside --}}
        @include('partials.aside')

        {{-- Content --}}
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                <div class="mb-8">
                    <h1 class="text-2xl text-gray-800 font-medium">Statistics</h1>
                    <div class="flex flex-row mt-3 -mx-3">
                        <div class="w-full md:w-1/3 bg-white shadow overflow-hidden rounded-lg mx-3 px-4 py-2">
                            <p class="text-md text-gray-700 pt-4 pl-4">Active Clients</p>
                            <h1 class="text-4xl text-gray-900 font-medium pl-4 -mt-2 mb-2">{{ number_format($activeClients) }}</h1>
                        </div>
                        <div class="w-full md:w-1/3 bg-white shadow overflow-hidden rounded-lg mx-3 px-4 py-2">
                            <p class="text-md text-gray-700 pt-4 pl-4">Leads</p>
                            <h1 class="text-4xl text-gray-900 font-medium pl-4 -mt-2 mb-2">579</h1>
                        </div>
                        <div class="w-full md:w-1/3 bg-white shadow overflow-hidden rounded-lg mx-3 px-4 py-2">
                            <p class="text-md text-gray-700 pt-4 pl-4">Pending</p>
                            <h1 class="text-4xl text-gray-900 font-medium pl-4 -mt-2 mb-2">{{ number_format($pendingAppointments) }}</h1>
                        </div>
                    </div>
                </div>
                <div class="mb-8">
                    <h1 class="text-2xl text-gray-800 font-medium">Recent Activity</h1>
                    <div class="bg-white shadow overflow-hidden sm:rounded-lg mt-3">
                        @if ($recentActivities->count())
                            <div class="flex flex-col mt-5">
                                <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                                    <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
                                        <table class="min-w-full">
                                            <thead>
                                                <tr>
                                                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider" >
                                                        Name
                                                    </th>
                                                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider" >
                                                        Role
                                                    </th>
                                                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider" >
                                                        Email
                                                    </th>
                                                    <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider" >
                                                        Creation Date
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody class="bg-white">
                                                @foreach ($recentActivities as $activity)
                                                    <tr>
                                                        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-900">
                                                            {{ $activity->fullname }}
                                                        </td>
                                                        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-900">
                                                            {{ $role->title }}
                                                        </td>
                                                        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-900">
                                                            {{ $activity->email }}
                                                        </td>
                                                        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-200 text-sm leading-5 text-gray-900">
                                                            {{ $activity->created_at->diffForHumans() }}
                                                        </td>
                                                    </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        @else
                            <div class="bg-white shadow sm:rounded-lg p-5">
                                <h6>No entries yet.</h6>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/discovery-form.blade.php
@extends('layouts.app')

@section('title')
    Discovery Form Sample
@endsection

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
    <div class="flex">
        {{-- Aside --}}
        @include('partials.aside')
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            {{-- Nav --}}
            @include('partials.nav')
            <div class="bg-admin-gray h-screen p-5 md:pt-24 md:pb-10 md:pl-10 md:pr-10 z-10">
                {{-- Main --}}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
                        <h3 class="text-xl leading-6 font-medium text-gray-900"> Discovery Form Sample </h3>
                        <p class="mt-1 max-w-2xl text-sm leading-5 text-red-500 italic">
                            Please note that this is just a sample form for the triggering the discovery form api.
                        </p>
                    </div>
                    <form action="{{ route('discovery.trigger') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="type" value="public">
                        <div class="w-full md:w-5/6 px-4 py-5 border-b border-gray-200 sm:px-6">
                            <div class="flex flex-wrap -mx-3 mb-8">
                                <div class="w-full md:w-1/3 px-3 md:mb-0">
                                    <label class="block text-gray-700 font-medium mb-1" for="first_name"> First name <span class="text-red-500 text-md">*</span></label>
                                    <input type="text" name="first_name" id="first_name" value="{{ old('first_name') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('first_name') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white" autofocus>
                                    @error('first_name')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="w-full md:w-1/3 px-3">
                                    <label class="block text-gray-700 font-medium mb-1" for="last_name"> Last name </label>
                                    <input type="text" name="last_name" id="last_name" value="{{ old('last_name') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('last_name') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                                    @error('last_name')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="w-full md:w-2/4 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="email"> Email address <span class="text-red-500 text-md">*</span></label>
                                <input type="email" name="email" id="email" value="{{ old('email') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('email') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                                @error('email')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="flex flex-col mb-5">
                                <div class="md:w-1/3"></div>
                                <label class="md:w-2/3 block">
                                    <input class="mr-2 leading-tight" type="checkbox" name="appointment" id="appointment" @if(old('appointment') !== null) checked @endif>
                                    <label class="text-gray-700 font-medium text-lg" for="appointment">
                                        Schedule an appointment
                                    </label>
                                </label>
                            </div>
                            <div class="flex flex-wrap -mx-3 mb-8">
                                <div class="w-full md:w-1/3 px-3" id="appointment_type_field">
                                    <label class="block text-gray-700 font-medium mb-1" for="type"> Appointment Type <span class="text-red-500 text-md">*</span></label>
                                    <div class="relative">
                                        <select name="appointment_type" id="appointment_type" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('appointment_type') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                                            <option value="consultation-call" @if (old('appointment_type') === null || old('appointment_type') === "consultation-call") selected @endif> Consultation Call </option>
                                            <option value="others" @if (old('appointment_type') === "others") selected @endif> Others </option>
                                        </select>
                                        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                                        </div>
                                    </div>
                                    @error('appointment_type')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="w-full md:w-1/3 px-3" id="appointment_date_time_field">
                                    <label class="block text-gray-700 font-medium mb-1" for="appointment_date_time"> Date / Time <span class="text-red-500 text-md">*</span></label>
                                    <input type="datetime-local" name="appointment_date_time" id="appointment_date_time" value="{{ old('appointment_date_time') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('appointment_date_time') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                                    @error('appointment_date_time')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="flex justify-end bg-gray-100 px-8 py-3">
                            <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-8 rounded-md"> Submit </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            addOrRemoveAppointmentFields()
        })
        $('#appointment').on('change', function () {
            addOrRemoveAppointmentFields()
        })

        function addOrRemoveAppointmentFields() {
            if ($('#appointment').is(':checked')) {
                $('#appointment_type_field').removeClass('hidden')
                $('#appointment_date_time_field').removeClass('hidden')
            } else {
                $('#appointment_type_field').addClass('hidden')
                $('#appointment_date_time_field').addClass('hidden')
            }
        }
    </script>
@endpush

resources/views/setting.blade.php
@extends('layouts.app')

@section('title')
    Settings
@endsection

@section('content')
    <div class="flex">

        {{-- Aside --}}
        @include('partials.aside')

        {{-- Content --}}
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                <h1 class="text-2xl font-bold">Settings</h1>
                <div class="bg-white shadow overflow-hidden sm:rounded-lg mt-5">
                </div>
            </div>
        </div>

    </div>
@endsection