routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['throttle:60,1'])->namespace('Auth')->group(function() {
    Route::get('/login/google', 'LoginController@google')->name('google.login');
    Route::get('/login/google/callback', 'LoginController@googleCallback')->name('google.callback');
});

Route::redirect('/', '/login');

Route::get('dashboard', 'DashboardController@index')->name('dashboard');
Route::post('search', 'DashboardController@suggestions')->name('search.suggestions');

Route::get('asana', 'AsanaServiceController')->name('asana');

Route::resource('appointments', 'AppointmentController');
Route::resource('clients', 'ClientController');
Route::resource('users', 'UserController');
Route::resource('settings', 'SettingController');

Route::prefix('')->group(function() {
    Route::resource('invoices', 'InvoiceController');
    Route::get('quickbooks/invoice', 'InvoiceController@invoice')->name('invoices.quickbooks');
    Route::get('quickbooks/invoice/callback', 'InvoiceController@invoiceCallback')->name('invoices.quickbooks.callback');
    Route::get('quickbooks/invoice/{invoice}/void', 'InvoiceController@void')->name('invoice.void');
    Route::get('quickbooks/invoice/{invoice}/sendemail', 'InvoiceController@sendEmail')->name('invoice.send');
});

Route::prefix('')->group(function() {
    Route::resource('templates', 'TemplateController');
    Route::get('/{template}/fill', 'TemplateController@fill')->name('templates.fill');
    Route::post('/ckeditor/upload', 'TemplateController@uploadImage')->name('templates.ckeditor.upload');
});

Route::name('mail.')->prefix('mail')->group(function() {
    Route::get('/', 'MailController@compose')->name('compose');
    Route::post('/send', 'MailController@send')->name('send');
});

Route::put('clients/{client}/archive', 'ClientController@archive')->name('clients.archive');
Route::put('appointments/{appointment}/done', 'AppointmentController@done')->name('appointments.done');
Route::put('appointments/{appointment}/cancel', 'AppointmentController@cancel')->name('appointments.cancel');

Route::name('selections.')->prefix('selections')->group(function() {
    Route::get('tags', 'SelectController@tags')->name('tags');
    Route::get('clients', 'SelectController@clients')->name('clients');
    Route::get('templates', 'SelectController@templates')->name('templates');
    Route::get('groups', 'SelectController@groups')->name('groups');
    Route::get('roles', 'SelectController@roles')->name('roles');
});

// Temporary routes for discovery form
Route::view('discovery-form', 'discovery-form')->name('discovery.form');
Route::post('/discovery-call-intake', 'API\DiscoveryController@trigger')->name('discovery.trigger');

app/Invoice.php
<?php

namespace App;

use Carbon\Carbon;
use App\Scopes\VoidedScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Invoice extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'qb_invoice_id', 'invoice_link', 'bill_email'
    ];

    protected static function booted()
    {
        static::addGlobalScope(new VoidedScope);
    }

    public function getLastUpdatedAttribute()
    {
    	return Carbon::parse("$this->updated_at")->format('F d, Y h:i A');
    }

    public function getCreatedAttribute()
    {
    	return Carbon::parse("$this->created_at")->format('F d, Y h:i A');
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\Invoice as InvoiceModel;
use App\Traits\Quickbooks;
use App\Http\Requests\InvoiceStore;
use App\Http\Requests\InvoiceUpdate;

use Throwable;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use QuickBooksOnline\API\Facades\Invoice;

class InvoiceController extends Controller
{
    use Quickbooks;

    public function __construct() 
    {
        $this->middleware('quickbooks')->except(['invoice', 'invoiceCallback']);
    }

    public function index()
    {
        return view('invoices.index')->withInvoices(InvoiceModel::paginate());
    }

    public function create()
    {
        return view('invoices.create');
    }

    public function store(InvoiceStore $request)
    {
        DB::beginTransaction();

        try {
            $newInvoice = Invoice::create([
                "Line" => [
                    [
                        "Amount" => number_format($request->amount, 2),
                        "DetailType" => "SalesItemLineDetail",
                        "SalesItemLineDetail" => [
                            "ItemRef" => [
                                "name" => $request->service_name,
                                "value" => 1
                            ]
                        ]
                    ]
                ],
                "CustomerRef"=> [
                    "value"=> 1
                ],
                "BillEmail" => [
                    "Address" => $request->bill_email
                ],
                "BillEmailCc" => [
                    "Address" => "a@intuit.com"
                ],
                "BillEmailBcc" => [
                    "Address" => "v@intuit.com"
                ]
            ]);
            $response = $this->dataService()->Add($newInvoice);

            // Save Invoice details
            $invoice = new InvoiceModel;
            $invoice->qb_invoice_id = $response->Id;
            $invoice->invoice_link = $response->InvoiceLink;
            $invoice->bill_email = $response->BillEmail->Address;
            $invoice->service_name = $request->service_name;
            $invoice->save();

        } catch (Throwable $th) {

            DB::rollBack();
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        DB::commit();
        return redirect()->route('invoices.index');
    }

    public function show()
    {
        try {
            $invoice = $this->dataService()->FindbyId('invoice', 196);

        } catch (Throwable $th) {
    
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        return view('invoices.show')->withInvoice($invoice);
    }

    public function edit($id)
    {   
        try {
            $invoice = $this->dataService()->FindbyId('invoice', $id);
            $invoiceLocalDetail = InvoiceModel::where('qb_invoice_id', $id)->first();

        } catch (Throwable $th) {
    
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        return view('invoices.edit')->with(['invoice' => $invoice, 'localDetail' => $invoiceLocalDetail]);
    }

    public function update(InvoiceUpdate $request, $id)
    {
        try {
            $invoiceLocalDetail = InvoiceModel::find($id);
            $invoice = $this->dataService()->FindbyId('invoice', $invoiceLocalDetail->qb_invoice_id);

            $updatedInvoice = Invoice::update($invoice, [
                "Line" => [
                    [
                        "Amount" => number_format($request->amount, 2),
                        "DetailType" => "SalesItemLineDetail",
                        "SalesItemLineDetail" => [
                            "ItemRef" => [
                                "name" => $invoiceLocalDetail->service_name,
                                "value" => 1
                            ]
                        ]
                    ]
                ],
                "CustomerRef"=> [
                    "value"=> 2
                ],
                "BillEmail" => [
                    "Address" => $request->bill_email
                ],
                "BillEmailCc" => [
                    "Address" => "abc@intuit.com"
                ],
                "BillEmailBcc" => [
                    "Address" => "vxyz@intuit.com"
                ]
            ]);
    
            $response = $this->dataService()->Update($updatedInvoice);

            $invoice = $invoiceLocalDetail;
            $invoice->qb_invoice_id = $response->Id;
            $invoice->invoice_link = $response->InvoiceLink;
            $invoice->bill_email = $response->BillEmail->Address;
            $invoice->service_name = $request->service_name;
            $invoice->save();
    
        } catch (Throwable $th) {
    
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        return redirect()->route('invoices.index');
    }

    public function destroy($id)
    {
        try {
            $localDetail = InvoiceModel::find($id);
            $invoice = $this->dataService()->FindbyId('invoice', $localDetail->qb_invoice_id);
            $response = $this->dataService()->Delete($invoice);

            InvoiceModel::destroy($id);
    
        } catch (Throwable $th) {
    
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        return back();
    }

    public function void($id){
        try {
            $localDetail = InvoiceModel::find($id);
            $invoice = $this->dataService()->FindbyId('invoice', $localDetail->qb_invoice_id);
            $response = $this->dataService()->Void($invoice);

            $localDetail->voided_at = Carbon::now();
            $localDetail->save();
    
        } catch (Throwable $th) {
    
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        return back();
    }

    public function sendEmail($id){
        try{
            $invoice = $this->dataService()->FindById("invoice", $id);
            $this->dataService()->SendEmail($invoice, $invoice->BillEmail->Address);
        }catch(Throwable $th){
            Log::error($th->getMessage());
            return back()->withErrors(['Something went wrong. Please contact support.']);
        }

        return redirect()->back();
    }

}

resources/views/invoices/create.blade.php
@extends('layouts.app')

@section('title')
    Create Invoice
@endsection

@section('content')
    <div class="flex">
        {{-- Aside --}}
        @include('partials.aside')
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            {{-- Nav --}}
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                {{-- Main --}}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
                        <h3 class="text-xl leading-6 font-medium text-gray-900"> Client Invoice </h3>
                        <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
                            Create invoice for existing client.
                        </p>
                    </div>
                    <form action="{{ route('invoices.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full md:w-5/6 px-4 py-5 border-b border-gray-200 sm:px-6">
                            <div class="w-full md:w-2/3 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="service_name"> Service Name <span class="text-red-500 text-md">*</span></label>
                                <input type="text" name="service_name" id="service_name" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('service_name') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" required autofocus>
                                @error('service_name')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="w-full md:w-2/3 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="bill_email"> Email address <span class="text-red-500 text-md">*</span></label>
                                <input type="email" name="bill_email" id="bill_email" value="{{ old('bill_email') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('bill_email') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" required>
                                @error('bill_email')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="w-full md:w-2/3 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="amount"> Amount <span class="text-red-500 text-md">*</span></label>
                                <input type="number" name="amount" id="amount" value="{{ old('amount') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('amount') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" required>
                                @error('amount')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="flex justify-end bg-gray-100 px-8 py-3">
                            <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-8 rounded-md"> Save </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoices/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Invoice
@endsection

@section('content')
    <div class="flex">
        {{-- Aside --}}
        @include('partials.aside')
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            {{-- Nav --}}
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                {{-- Main --}}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
                        <h3 class="text-xl leading-6 font-medium text-gray-900"> Edit Invoice </h3>
                        <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
                            Edit invoice of an client.
                        </p>
                    </div>
                    <form action="{{ route('invoices.update') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full md:w-5/6 px-4 py-5 border-b border-gray-200 sm:px-6">
                            <div class="w-full md:w-2/3 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="service_name"> Service Name <span class="text-red-500 text-md">*</span></label>
                                <input type="text" name="service_name" id="service_name" value="{{ old('service_name') ?? $invoice->service_name }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('service_name') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" required autofocus>
                                @error('service_name')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="w-full md:w-2/3 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="bill_email"> Email address <span class="text-red-500 text-md">*</span></label>
                                <input type="email" name="bill_email" id="bill_email" value="{{ old('bill_email') ?? $invoice->bill_email }} }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('bill_email') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" required>
                                @error('bill_email')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="w-full md:w-2/3 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="amount"> Amount <span class="text-red-500 text-md">*</span></label>
                                <input type="number" name="amount" id="amount" value="{{ old('amount') ?? $invoice->amount }} }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('amount') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" required>
                                @error('amount')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="flex justify-end bg-gray-100 px-8 py-3">
                            <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-8 rounded-md"> Save </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoices/index.blade.php
@extends('layouts.app')

@section('title')
    Invoices
@endsection

@section('content')
    <div class="flex">

        {{-- Aside --}}
        @include('partials.aside')

        {{-- Content --}}
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            @include('partials.nav')
            <div class="bg-admin-gray @if ($invoices->count()) h-full @else h-screen @endif p-5 md:pt-24 md:pb-10 md:pl-10 md:pr-10 z-10">
                <div class="flex items-center justify-end mb-5">
                    <div>
                        <a href="{{ route('invoices.create') }}" class="px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out">Create New</a>
                    </div>
                </div>
                <div class="flex items-center justify-between mb-2">
                    <h1 class="text-2xl font-medium"> Invoice List </h1>
                </div>
                <div class="flex flex-col">
                    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                                <table class="min-w-full divide-y divide-gray-200">
                                    <thead>
                                        <tr>
                                            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                                Bill Email
                                            </th>
                                            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                                Last Updated
                                            </th>
                                            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                                Created
                                            </th>
                                            <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody class="bg-white divide-y divide-gray-200">
                                        @forelse ($invoices as $invoice)
                                            <tr>
                                                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                                                    {{ $invoice->bill_email }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                                                    {{ $invoice->last_updated }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                                                    {{ $invoice->created }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
                                                    <a href="{{ route('invoices.send', $invoice->id) }}" class="text-indigo-600 hover:text-indigo-900">
                                                        Send
                                                    </a>
                                                    <a href="{{ route('invoices.edit', $invoice->id) }}" class="text-indigo-600 hover:text-indigo-900">
                                                        Edit
                                                    </a>
                                                    <a href="{{ route('invoices.void', $invoice->id) }}" class="text-indigo-600 hover:text-indigo-900">
                                                        Void
                                                    </a>
                                                    <a href="{{ route('invoices.destroy', $invoice->id) }}" class="text-indigo-600 hover:text-indigo-900"
                                                        onclick="event.preventDefault();
                                                            document.getElementById('destroy-form-{{ $invoice->id }}').submit();">
                                                        Delete
                                                    </a>
                                                    <form id="destroy-form-{{ $invoice->id }}" action="{{ route('invoices.destroy', $invoice->id) }}" method="POST" class="d-none">
                                                        @csrf
                                                        @method("DELETE")
                                                    </form>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td class="px-6 py-4 whitespace-no-wrap" colspan="5">
                                                    <i> No entries yet </i>
                                                </td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                                @if ($invoices->count())
                                    <div class="m-2 px-3">
                                        {{ $invoices->withQueryString()->links('pagination::tailwind') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/invoices/show.blade.php
@extends('layouts.app')

@section('title')
    Invoice Information
@endsection

@section('content')
    <div class="flex">
        {{-- Aside --}}
        @include('partials.aside')
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            {{-- Nav --}}
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                {{-- Main --}}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="flex justify-between items-center border-b border-gray-200 p-8">
                        <div>
                            <h3 class="text-xl leading-6 font-medium text-gray-900"> Invoice Information </h3>
                            <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
                                Invoice details and description.
                            </p>
                        </div>
                        <div>
                            <a href="{{ route('invoices.edit', $invoice->id) }}" class="rounded-lg border border-gray-400 inline-flex items-center py-2 px-5 mr-3">
                                <svg class="w-6 h-6 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
                                <span class="text-lg">Edit</span>
                            </a>
                        </div>
                    </div>
                    <div class="border-b border-gray-200 p-8">
                        Invoice Show
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection