routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['throttle:60,1'])->namespace('Auth')->group(function() {
    Route::get('/login/google', 'LoginController@google')->name('google.login');
    Route::get('/login/google/callback', 'LoginController@googleCallback')->name('google.callback');
});

Route::redirect('/', '/login');

Route::get('dashboard', 'DashboardController@index')->name('dashboard');
Route::post('search', 'DashboardController@suggestions')->name('search.suggestions');

Route::get('asana', 'AsanaServiceController')->name('asana');

Route::resource('appointments', 'AppointmentController');
Route::resource('clients', 'ClientController');
Route::resource('users', 'UserController');
Route::resource('settings', 'SettingController');

Route::prefix('')->group(function() {
    Route::resource('invoices', 'InvoiceController');
    Route::get('quickbooks/invoice', 'InvoiceController@invoice')->name('invoices.quickbooks');
    Route::get('quickbooks/invoice/callback', 'InvoiceController@invoiceCallback')->name('invoices.quickbooks.callback');
    Route::get('quickbooks/invoice/{invoice}/void', 'InvoiceController@void')->name('invoice.void');
    Route::get('quickbooks/invoice/{invoice}/sendemail', 'InvoiceController@sendEmail')->name('invoice.send');
});

Route::prefix('')->group(function() {
    Route::resource('templates', 'TemplateController');
    Route::get('/{template}/fill', 'TemplateController@fill')->name('templates.fill');
    Route::post('/ckeditor/upload', 'TemplateController@uploadImage')->name('templates.ckeditor.upload');
});

Route::name('mail.')->prefix('mail')->group(function() {
    Route::get('/', 'MailController@compose')->name('compose');
    Route::post('/send', 'MailController@send')->name('send');
});

Route::put('clients/{client}/archive', 'ClientController@archive')->name('clients.archive');
Route::put('appointments/{appointment}/done', 'AppointmentController@done')->name('appointments.done');
Route::put('appointments/{appointment}/cancel', 'AppointmentController@cancel')->name('appointments.cancel');

Route::name('selections.')->prefix('selections')->group(function() {
    Route::get('tags', 'SelectController@tags')->name('tags');
    Route::get('clients', 'SelectController@clients')->name('clients');
    Route::get('templates', 'SelectController@templates')->name('templates');
    Route::get('groups', 'SelectController@groups')->name('groups');
    Route::get('roles', 'SelectController@roles')->name('roles');
});

// Temporary routes for discovery form
Route::view('discovery-form', 'discovery-form')->name('discovery.form');
Route::post('/discovery-call-intake', 'API\DiscoveryController@trigger')->name('discovery.trigger');

resources/views/templates/create.blade.php
@extends('layouts.app')

@section('title')
    Create Template
@endsection

@push('head')
    <script src="https://cdn.ckeditor.com/4.12.1/standard/ckeditor.js"></script>
@endpush

@push('styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endpush

@section('content')
    <div class="flex">
        {{-- Aside --}}
        @include('partials.aside')
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            {{-- Nav --}}
            @include('partials.nav')
            <div class="p-5 md:p-10 z-10 mt-16 bg-admin-gray h-full">
                {{-- Main --}}
                <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
                        <h3 class="text-xl leading-6 font-medium text-gray-900"> Create Template </h3>
                        <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
                            Create reusable email template.
                        </p>
                    </div>
                    <form action="{{ route('templates.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="w-full md:w-5/6 px-4 py-5 border-b border-gray-200 sm:px-6">
                            <div class="flex flex-wrap -mx-3 mb-8">
                                <div class="w-full md:w-1/2 px-3 md:mb-0">
                                    <label class="block text-gray-700 font-medium mb-1" for="name"> Template name <span class="text-red-500 text-md">*</span></label>
                                    <input type="text" name="name" id="name" value="{{ old('name') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('name') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white" autofocus>
                                    @error('name')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="w-full md:w-1/2 px-3 md:mb-0">
                                    <label class="block text-gray-700 font-medium mb-1" for="keyword"> Keyword </label>
                                    <input type="text" name="keyword" id="keyword" value="{{ old('keyword') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('keyword') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white">
                                    @error('keyword')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="flex flex-col mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="body"> Template content <span class="text-red-500 text-md">*</span></label>
                                <textarea name="body" id="body" class="border-2 rounded w-full" cols="30" rows="10">{{ old('body') }}</textarea>
                            </div>
                            <label class="block text-gray-700 font-medium mb-1" for="attachments"> Add attachments </label>
                            <div class="border border-dashed border-gray-500 relative mb-5">
                                <input type="file" name="attachments[]" id="attachments" value="{{ old('attachments') }}" multiple class="cursor-pointer relative block opacity-0 w-full h-full p-20 z-50">
                                <div class="text-center p-10 absolute top-0 right-0 left-0 m-auto">
                                    <h4>
                                        <span class="text-indigo-500">Upload a file</span> or drag and drop
                                        <br> PNG, JPG, up to 10mb 
                                    </h4>
                                </div>
                            </div>
                            <div class="flex flex-col mb-8 hidden" id="attachmentsDiv">
                                <label class="block text-gray-700 font-medium mb-1"> Attachments </label>
                                <div class="flex flex-col mb-1" id="attachmentBody"></div>
                            </div>
                            <div class="w-full mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="subject"> Subject </label>
                                <input type="text" name="subject" id="subject" value="{{ old('subject') }}" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('subject') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">
                                @error('subject')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                            <div class="flex flex-wrap -mx-3 mb-8">
                                <div class="w-full md:w-1/3 px-3 md:mb-0">
                                    <label class="block text-gray-700 font-medium mb-1" for="to"> To </label>
                                    <select class="w-full" name="to[]" id="to" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('to') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" multiple>
                                        @foreach ((array) old('to') as $to)
                                            <option value="{{ $to }}" selected> {{ $to }} </option>
                                        @endforeach
                                    </select>
                                    @error('to')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="w-full md:w-1/3 px-3 md:mb-0">
                                    <label class="block text-gray-700 font-medium mb-1" for="cc"> Cc </label>
                                    <select class="w-full" name="cc[]" id="cc" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('cc') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" multiple>
                                        @foreach ((array) old('cc') as $cc)
                                            <option value="{{ $cc }}" selected> {{ $cc }} </option>
                                        @endforeach
                                    </select>
                                    @error('cc')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                                <div class="w-full md:w-1/3 px-3 md:mb-0">
                                    <label class="block text-gray-700 font-medium mb-1" for="bcc"> Bcc </label>
                                    <select class="w-full" name="bcc[]" id="bcc" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('bcc') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" multiple>
                                        @foreach ((array) old('bcc') as $bcc)
                                            <option value="{{ $bcc }}" selected> {{ $bcc }} </option>
                                        @endforeach
                                    </select>
                                    @error('bcc')
                                        <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="w-full md:w-1/2 mb-8">
                                <label class="block text-gray-700 font-medium mb-1" for="tags"> Tags </label>
                                <select name="tags[]" id="tags" class="appearance-none block w-full text-gray-700 border border-gray-400 @error ('tags') border-red-500 @enderror rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500" multiple></select>
                                @error('tags')
                                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <div class="flex justify-end bg-gray-100 px-8 py-3">
                            <button type="submit" class="bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-8 rounded-md"> Save </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('js/insert_variable.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('select').select2({
                tags: true,
                tokenSeparators: [',', ' ']
            })
            $('#to').select2({
                tags: true,
                tokenSeparators: [',', ' '],
                maximumSelectionLength: 1
            })
            $('#tags').select2({
                ajax: {
                    url: "{{ route('selections.tags') }}",
                    dataType: 'json',
                    processResults: function (data) {
                        return {
                            results: data.results
                        }
                    },
                    delay: 250,
                    cache: true,
                },
                minimumInputLength: 1,
                tags: true,
                tokenSeparators: [',']
            });

            $('input#attachments').on('change', function(){
                let attachments = Array.from(this.files).map(function(f) {
                    return f.name;
                });

                $.each(attachments, function(index, el) {
                    console.log($('#attachments').val())
                    let attachment = `
                                    <div class="w-full flex justify-between items-center border border-gray-400 ${attachments.length } px-5 py-3">
                                        <div class="flex flex-row items-center">
                                            <svg class="w-8 h-8 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                                            ${el}
                                        </div>
                                    </div>`;

                    $('div#attachmentBody').append(attachment)
                    $('div#attachmentsDiv').show()
                });
            })
        });

        CKEDITOR.replace('body', {
            filebrowserImageUploadUrl: "{{ route('templates.ckeditor.upload', ['_token' => csrf_token() ])}}",
            filebrowserUploadMethod: 'form',
            extraPlugins: 'insert_variable',
            insert_variable: {
                variables: [
                    'To: First Name',
                    'To: Email',
                    'From: First Name',
                    'From: Email',
                ]
            },
        });
    </script>
@endpush

resources/views/templates/index.blade.php
@extends('layouts.app')

@section('title')
    Email Templates
@endsection

@section('content')
    <div class="flex">

        {{-- Aside --}}
        @include('partials.aside')

        {{-- Content --}}
        <div class="w-5/6 md:w-4/5 absolute right-0 top-0">
            @include('partials.nav')
            <div class="bg-admin-gray @if ($templates->count() > 5) h-full @else h-screen @endif p-5 md:pt-24 md:pb-10 md:pl-10 md:pr-10 z-10">
                <div class="flex items-center justify-between mb-5">
                    <div>
                        <form method="GET" class="inline" id="templates-search">
                            <input class="bg-white appearance-none border border-gray-300 rounded py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white" type="text" id="search-templates" name="search" value="{{ request('search') }}" placeholder="Search templates">
                        </form>
                        <div class="relative inline-block text-left">
                            <div>
                                <span class="rounded-md shadow-sm">
                                    <button type="button" class="inline-flex justify-center w-full rounded border border-gray-300 px-4 py-2 bg-gray-100 text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition ease-in-out duration-150" id="sort" aria-haspopup="true" aria-expanded="true">
                                        Sort
                                        <svg class="-mr-1 ml-2 h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            </div>
                            <div class="origin-top-right absolute left-0 mt-2 w-56 rounded-md shadow-lg hidden" id="sort-dropdown">
                                <div class="rounded-md bg-white shadow-xs">
                                    <div class="py-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
                                        <a href="{{ route('templates.index', ['sort' => 'name', 'search' => request('search'), 'desc' => request('desc')]) }}" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900" role="menuitem">
                                            Name
                                        </a>
                                        <a href="{{ route('templates.index', ['sort' => 'keyword', 'search' => request('search'), 'desc' => request('desc')]) }}" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900" role="menuitem">
                                            Keyword
                                        </a>
                                        <a href="{{ route('templates.index', ['sort' => 'created_at', 'search' => request('search'), 'desc' => request('desc')]) }}" class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus:bg-gray-100 focus:text-gray-900" role="menuitem">
                                            Creation Date
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <a href="{{ route('templates.create') }}" class="px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700 transition duration-150 ease-in-out">New Template</a>
                    </div>
                </div>
                @forelse($templates as $template)
                    <div class="card text-white bg-admin-blue-light overflow-hidden sm:rounded-lg mt-5">
                      <div class="card-body p-2">
                        <h1 class="text-2xl font-bold p-2 pb-0">{{ $template->name }}</h1>
                        <div class="flex items-center justify-between">
                            <div class="flex items-center">
                                <div class="flex p-2">
                                    <svg class="w-6 h-6 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z"></path></svg>
                                    @if ($template->keyword)
                                        <p> {{ $template->keyword }} </p>
                                    @else
                                        <i> No keyword </i>
                                    @endif
                                </div>
                                <div class="flex align-center p-2">
                                    <svg class="w-6 h-6 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"></path></svg>
                                    @if ($template->tags->count())
                                        <p>
                                            @foreach ($template->tags as $tag)
                                                {{ $tag->name }} &nbsp;
                                            @endforeach
                                        </p>
                                    @else
                                        <i>No tags</i>
                                    @endif
                                </div>
                            </div>
                            <div class="flex items-center">
                                <a href="{{ route('templates.edit', $template->id) }}" class="px-5 py-2 bg-gray-500 text-white font-bold rounded-lg m-2 flex">
                                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
                                    Edit
                                </a>
                                <a class="px-5 py-2 bg-red-500 text-white font-bold rounded-lg m-2 flex" href="{{ route('templates.destroy', $template->id) }}"
                                    onclick="event.preventDefault();
                                                document.getElementById('destroy-form-{{ $template->id }}').submit();">
                                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                                    Delete
                                </a>
                                <form id="destroy-form-{{ $template->id }}" action="{{ route('templates.destroy', $template->id) }}" method="POST" class="d-none">
                                    @csrf
                                    @method("DELETE")
                                </form>
                            </div>
                        </div>
                      </div>
                    </div>
                @empty
                    <div class="bg-white shadow sm:rounded-lg p-5 mt-5">
                        <h6>No entries yet.</h6>
                    </div>
                @endforelse
                <div class="m-3 px-3">
                    {{ $templates->withQueryString()->links('pagination::tailwind') }}
                </div>
            </div>
        </div>

    </div>
@endsection

@push('scripts')
    <script>
        $('#sort').on('click', function() {
            $('#sort-dropdown').toggle('hidden')
        })
    </script>
@endpush